### ISSUE TITLE
Exporter ignores normals and always exports fully smoothed model

### ISSUE THREAD

**Issue by ssnd292** [StjerneIdioten/I3d-Import-Export-Giants#9]
When exporting custom meshes, the exporter ignores the smoothing set in Blender (be it custom weighted vertex normals via modifier, auto smoothing in data properties, manual smoothing via hard and soft edges or even hard edges set by HardOps addon)

Desired effect is that the exporter keeps the normal information and treats it as is, see attached picture.

![2020-02-01 00_09_14-GIANTS Editor 64bit 8 1 0 - E__Modding_FS19_EFGC195_i3d_MulcherEFGCSeries_GEExpo](https://user-images.githubusercontent.com/3914410/73580827-57a61f80-4487-11ea-882d-e384ed4e212a.jpg)

**Comment by ssnd292** [comment]
Is State in Blender
![2020-02-01 00_27_08-Blender  E__Modding_FS19_Exporter_EdgeSmoothing blend](https://user-images.githubusercontent.com/3914410/73581507-bc627980-4489-11ea-8274-58e4ef153eec.jpg)

State when Exporting with i3d Exporter
![2020-02-01 00_27_25-GIANTS Editor 64bit 8 1 0 - E__Modding_FS19_Exporter_EdgeSmoothing_Exporter i3d](https://user-images.githubusercontent.com/3914410/73581517-c5534b00-4489-11ea-8f62-8735456649a6.jpg)

Desired state when exporting as FBX and importing into Giants Editor
![2020-02-01 00_27_50-GIANTS Editor 64bit 8 1 0 - E__Modding_FS19_Exporter_EdgeSmoothing_FBX i3d](https://user-images.githubusercontent.com/3914410/73581529-cedcb300-4489-11ea-8cb3-4b5ac3f5d61a.jpg)

i3d files and Blender file to test it out
[EdgeSmoothing.zip](https://github.com/StjerneIdioten/I3d-Import-Export-Giants/files/4141852/EdgeSmoothing.zip)

**Comment by StjerneIdioten** [comment]
The blend file you have sent does not match the data exported in the fbx exporter. At least not on specular settings :P

**Comment by ssnd292** [comment]
[EdgeSmoothing.zip](https://github.com/StjerneIdioten/I3d-Import-Export-Giants/files/4142458/EdgeSmoothing.zip)

Try this
